name: Build Python Package
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  test:
    name: Build Python Package
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: python setup.py sdist bdist_wheel
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/
